// Code generated by protoc-gen-go.
// source: keyboard_message.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	keyboard_message.proto
	laptop_message.proto
	memory_message.proto
	processor_message.proto
	screen_message.proto
	storage_message.proto

It has these top-level messages:
	Keyboard
*/
package pb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Keyboard_Layout int32

const (
	Keyboard_UNKNOWN Keyboard_Layout = 0
	Keyboard_QUERTY  Keyboard_Layout = 1
	Keyboard_QUERTZ  Keyboard_Layout = 2
	Keyboard_AZERTY  Keyboard_Layout = 3
)

var Keyboard_Layout_name = map[int32]string{
	0: "UNKNOWN",
	1: "QUERTY",
	2: "QUERTZ",
	3: "AZERTY",
}
var Keyboard_Layout_value = map[string]int32{
	"UNKNOWN": 0,
	"QUERTY":  1,
	"QUERTZ":  2,
	"AZERTY":  3,
}

func (x Keyboard_Layout) String() string {
	return proto.EnumName(Keyboard_Layout_name, int32(x))
}

type Keyboard struct {
	Layout  Keyboard_Layout `protobuf:"varint,1,opt,name=layout,enum=grpc.pb.Keyboard_Layout" json:"layout,omitempty"`
	Backlit bool            `protobuf:"varint,2,opt,name=backlit" json:"backlit,omitempty"`
}

func (m *Keyboard) Reset()         { *m = Keyboard{} }
func (m *Keyboard) String() string { return proto.CompactTextString(m) }
func (*Keyboard) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("grpc.pb.Keyboard_Layout", Keyboard_Layout_name, Keyboard_Layout_value)
}
