// Code generated by protoc-gen-go.
// source: processor_message.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type CPU struct {
	Brand         string  `protobuf:"bytes,1,opt,name=brand" json:"brand,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NumberThreads uint32  `protobuf:"varint,4,opt,name=number_threads" json:"number_threads,omitempty"`
	NumberCores   uint32  `protobuf:"varint,3,opt,name=number_cores" json:"number_cores,omitempty"`
	MinGhz        float64 `protobuf:"fixed64,5,opt,name=min_ghz" json:"min_ghz,omitempty"`
	MaxGhz        float64 `protobuf:"fixed64,6,opt,name=max_ghz" json:"max_ghz,omitempty"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}

type GPU struct {
	Brand  string  `protobuf:"bytes,1,opt,name=brand" json:"brand,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	MinGhz float64 `protobuf:"fixed64,3,opt,name=min_ghz" json:"min_ghz,omitempty"`
	MaxGhz float64 `protobuf:"fixed64,4,opt,name=max_ghz" json:"max_ghz,omitempty"`
	Memory *Memory `protobuf:"bytes,5,opt,name=memory" json:"memory,omitempty"`
}

func (m *GPU) Reset()         { *m = GPU{} }
func (m *GPU) String() string { return proto.CompactTextString(m) }
func (*GPU) ProtoMessage()    {}

func (m *GPU) GetMemory() *Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func init() {
}
